#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S2,     HTSMUX,         sensorI2CCustom)
#pragma config(Sensor, S3,     IRS_R,          sensorI2CCustom)
#pragma config(Sensor, S4,     IRS_L,          sensorNone)
#pragma config(Motor,  mtr_S1_C1_1,     mDriveLeft,    tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     mDriveRight,   tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     mBsConveyor,   tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     mBsAngle,      tmotorTetrix, openLoop, encoder)
#pragma config(Servo,  srvo_S1_C3_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "autonomous-includes/autonomous_tasks.c"
#include "autonomous-includes/color_mode_picker.c"

//short autoMode = getAutoMode();

task main(){
	// do some housekeeping work. print that the program is running, clear the screen and debug stream
	bNxtLCDStatusDisplay = false;
	eraseDisplay();
	nxtDisplayBigTextLine(0, "Auto");
	nxtDisplayBigTextLine(2, "Mode");
	nxtDisplayBigTextLine(4, "Running");
	nxtDisplayTextLine(6, "Running task:");
	clearDebugStream();
	ClearTimer(T1);

	StartTask(getSmux); // run and update the sensor multiplexer

	if (autoMode == 1){
		StartTask(raiseSuckerToLevel);
	//	StartTask(findIr);

	//	while (foundIr == false){
	//		nxtDisplayTextLine(7, "findIr");
	//	}
	//	nxtDisplayTextLine(7, "None");
	//	StopTask(findIr);
	//	clearDebugStream();
	//	writeDebugStreamLine("IR beacon found.");

	//	writeDebugStreamLine("Turning...");
	//	turnXDegrees(90.0);
	//	wait10Msec(300);

	//	// this is where it places the block

	//	writeDebugStreamLine("Clockwise Turning...");
	//	turnXDegrees(-90.0);
	//	writeDebugStreamLine("Done. Stopping...");
	//	wait10Msec(300);
	}

}
