#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S3,     IRS_R,          sensorI2CCustom)
#pragma config(Sensor, S4,     IRS_L,          sensorI2CCustom)
#pragma config(Motor,  mtr_S1_C1_1,     mDriveLeft,    tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     mDriveRight,   tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     mBsConveyor,   tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     mBsAngle,      tmotorTetrix, openLoop, encoder)
#pragma config(Servo,  srvo_S1_C3_1,    sBrickStop,           tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.

#define FN(x)	((float)x * 0.78125)	// Convert the joystick's -128 - 127 value to a -99 - 100 value
#define MODE_STRAIGHT true
#define MODE_NOMRAL false

// Set all motors to the input value
void allMotorsTo(int i){
		motor[mDriveLeft] 	= i;
		motor[mDriveRight] 	= i;
		motor[mBsAngle] 		= i;
		motor[mBsConveyor] 	= i;
}

// Set all drive motors to the input value
void driveMotorsTo(int i){
		motor[mDriveLeft] 	= i;
		motor[mDriveRight] 	= i;
}

// Initialize robot positions
void initializeRobot()
{
	allMotorsTo(0);
  return;
}

// Global Variable declarations
short 	stickDriveLeft;
short 	stickDriveRight;
bool 		btnBsPower;
bool 		btnBsReverse;
bool 		btnBsRaise;
bool 		btnBsLower;
bool 		btnStraightDr;
bool		btnBrickStop;
bool		MODE_NORMAL;
bool		driveMode;
short		stickThreshold = 10;

int			blockClosedPos = 0;
int			blockOpenPos = 90;
int 		conveyorMotorSpeed = 100;
int 		towerMotorSpeed = 100;

// Function to transfer normal joystick values to the custom variables
void getCustomJoystickSettings(){
	stickDriveLeft 	= joystick.joy1_y1;
	stickDriveRight = joystick.joy1_y2;
	btnBsPower			= (joy2Btn(6) == 1);
	btnBsReverse 		= (joy2Btn(8) == 1);
	btnBsRaise 			= (joy2Btn(5) == 1);
	btnBsLower 			= (joy2Btn(7) == 1);
	btnStraightDr		= (joy1Btn(3) == 1);
	btnBrickStop		=	(joy2Btn(3) == 1);
}

// Print information to the screen
void displayButtonValues(){
	  nxtDisplayTextLine(0, "stDriveLeft:%d",		stickDriveLeft);
  	nxtDisplayTextLine(1, "stDriveRight:%d",	stickDriveRight);
  	nxtDisplayTextLine(2, "btnBsPower:%s",		(btnBsPower)?"1":"0");
  	nxtDisplayTextLine(3, "btnBsReverse:%s",	(btnBsReverse)?"1":"0");
  	nxtDisplayTextLine(4, "btnBsRaise:%s",		(btnBsRaise)?"1":"0");
  	nxtDisplayTextLine(5, "DriveMode:%s",			(driveMode)?"STRAIGHT":"NORMAL");
  	nxtDisplayTextLine(6, "mDrLeft:%3.1f",		motor[mDriveLeft]);
  	nxtDisplayTextLine(7, "mDrRight:%3.1f",		motor[mDriveRight]);
}



task main(){
	// Turn off battery level display on the NXT screen
	bNxtLCDStatusDisplay = false;

	eraseDisplay();		// Cear the screen
  initializeRobot();

  //waitForStart();   // wait for start of tele-op phase

  while (true){
  	getJoystickSettings(joystick);
  	getCustomJoystickSettings();
		displayButtonValues();


		// Changing drive mode
		if(btnStraightDr){
			driveMode = MODE_STRAIGHT;
		}
		else{
			driveMode = MODE_NORMAL;
		}


		// Straight drive mode
		if (driveMode == MODE_STRAIGHT){

			// STRAIGHT DRIVE
			if(abs(stickDriveLeft) > stickThreshold){
					driveMotorsTo(FN(stickDriveLeft));
			}
			else{
				driveMotorsTo(0);
			}

		}
		// Normal drive mode
		else if(driveMode == MODE_NORMAL){

			// LEFT DRIVE
			if(abs(stickDriveLeft) < stickThreshold){
				motor[mDriveLeft] = 0;
			}
			else{
				motor[mDriveLeft] = FN(stickDriveLeft);
			}

			// RIGHT DRIVE
			if(abs(stickDriveRight) < stickThreshold){
				motor[mDriveRight] = 0;
			}
			else{
				motor[mDriveRight] = FN(stickDriveRight);
			}
		}


		// Conveyor
		if( (btnBsPower && btnBsReverse) || (!btnBsPower && !btnBsReverse)){// up and down buttons both pressed or both released
			motor[mBsConveyor] = 0;
		}
		else if (btnBsPower){
			motor[mBsConveyor] = conveyorMotorSpeed;
		}
		else if (btnBsReverse){
			motor[mBsConveyor] = -1 * conveyorMotorSpeed;
		}


		// Brick Sucker raise/lower
		if((btnBsRaise && btnBsLower) || (!btnBsRaise && !btnBsLower)){ // raise/lower buttons both pressed or both released
			motor[mBsAngle] = 0;
		}
		else if (btnBsRaise){
			motor[mBsAngle] = towerMotorSpeed;
		}
		else if (btnBsLower){
			motor[mBsAngle] = -1 * towerMotorSpeed;
		}

		// Brick stopper servo
		if(btnBrickStop){
				servo[sBrickStop] = blockOpenPos;
		}else{
			servo[sBrickStop] = blockClosedPos;
		}
  }
}
