#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     SMUX,           sensorI2CCustom)
#pragma config(Sensor, S3,     sGyro,          sensorI2CHiTechnicGyro)
#pragma config(Sensor, S4,     sLiftStop,      sensorTouch)
#pragma config(Motor,  motorA,          mFlagRaise1,   tmotorNXT, openLoop)
#pragma config(Motor,  motorB,          mFlagRaise2,   tmotorNXT, openLoop)
#pragma config(Motor,  motorC,          mBlockStop,    tmotorNXT, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_1,     mDriveLeft,    tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     mDriveRight,   tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     mBsConveyor,   tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     mBsAngle,      tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Servo,  srvo_S1_C3_1,    rConveyorTight,       tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    rBlockDropLeft,       tServoStandard)
#pragma config(Servo,  srvo_S1_C3_3,    rBlockDropRight,      tServoStandard)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

		// 1 wheel rot = 1350 ticks
#include "JoystickDriver.c"
#include "autonomous-includes/autonomousTasks.h"
#include "autonomous-includes/autoMenu.h"
#include "autonomous-includes/powerStackerSplash.h"

task main(){

	//doPowerstackerSplash();
	StartTask(runMenuOffensive);
	initializeRobot();

	waitForStart();
	printMenuChoices();
	StartTask(showDebugInfo);
	StartTask(getSmux);

	// Is there a delay?
	if(delay > 0){
		writeDebugStreamLine("Wait detected");
		wait10Msec(delay * 100);		// Wait the amount of time given by the delay
		writeDebugStreamLine("Wait over");
	}

	// Are we going to place the block?
	//int basketPosition = 0;
	if(doIr){
		// Record the starting encoder position
		startEncoderPos = nMotorEncoder[mDriveRight];

		// Find the IR basket
		findIrContinuous();
		//findIrIncremental();

		// Are we going around the far end?
		if(goAround){
			writeDebugStreamLine("Going to far end of ramp");
			// Figure out how far we have to go to get to the far end of the ramp, and go that distance
			long farEncoderPos = startEncoderPos + inchesToTicks(65);
			goTicks(farEncoderPos - nMotorEncoder[mDriveRight], 100);
		}else{
			writeDebugStreamLine("Going to near end of ramp");
			// Figure out how far back we have to go to get to the near end of the ramp, and go that distance
			long nearEncoderPos = startEncoderPos - inchesToTicks(7);
			goTicks(-1 * (nMotorEncoder[mDriveRight] - nearEncoderPos), 100);
		}

		// Did we start near or far?
		if(startNear){
			// Turn clockwise
			turnDegrees(-90, 35);
			if(rampOtherSide)
				goTicks(inchesToTicks(36), 100);
			findWhiteLine();
			turnDegrees(90, 35);
		}else{
			// Turn counterclockwise
			turnDegrees(90, 35);
			if(rampOtherSide)
				goTicks(inchesToTicks(36), 100);
			findWhiteLine();
			turnDegrees(-90, 35);
		}

		// Go up the ramp
		goTicks(inchesToTicks(36), 100);
	}
	else
		writeDebugStreamLine("Did not do IR. You really should have.");
}
