#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S2,     SMUX,           sensorI2CCustom)
#pragma config(Sensor, S3,     sGyro,          sensorI2CHiTechnicGyro)
#pragma config(Sensor, S4,     IRS,            sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,          mBlockStop,    tmotorNXT, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_1,     mDriveLeft,    tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     mDriveRight,   tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     mBsConveyor,   tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     mBsAngle,      tmotorTetrix, openLoop, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
#include "autonomous-includes/autonomous_tasks.c"

// 1 wheel rotation = 1350 ticks

task main()
{
	eraseDisplay();
	clearDebugStream();
	nxtDisplayCenteredBigTextLine(0, "AUTO");
	nxtDisplayCenteredBigTextLine(2, "READY");
	nMotorEncoder[mDriveLeft] = 0;
	nMotorEncoder[mDriveRight] = 0;
	nMotorEncoder[mBsAngle] = 0;
	//long encoderHomeValue = nMotorEncoder[mDriveRight];
	const long distancePastBaskets = 6000;
	waitForStart();
	nxtDisplayCenteredBigTextLine(2, "RUNNING");
	StartTask(getSmux);
	StartTask(showDebugInfo);

	short basket = findIrLeft(50, 25, 25);	// Find the IR beacon from the left side, record distance
	//long distanceToHome = nMotorEncoder[mDriveRight];
	//suckerToDropPosition();				// Raise sucker to drop position
	//turnDegrees(90, 50);					// Turn left
	//spitBlock();									// Deposit the block
	//turnDegrees(-90, 50);					// Turn right
	//goTicks(distancePastBaskets - distanceToHome, 100);	// Move forward x ticks, where x = total number of ticks from the
	//turnDegrees(90, 50);	// Turn left									//start position to the ramp minus the number of ticks already traveled.
	//goTicks(2000, 100);		// Move forward
	//turnDegrees(90, 50);	// Turn left
	//goTicks(3000, 100);		// Move forward

}
