#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S2,     SMUX,           sensorI2CCustom)
#pragma config(Sensor, S3,     sGyro,          sensorI2CHiTechnicGyro)
#pragma config(Sensor, S4,     TMUX,           sensorAnalogInactive)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,          mBlockStop,    tmotorNXT, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_1,     mDriveLeft,    tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     mDriveRight,   tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     mBsConveyor,   tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     mBsAngle,      tmotorTetrix, openLoop, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#include "JoystickDriver.c"
#include "autonomous-includes/autonomous_tasks.c"

task main()
{
	eraseDisplay();
	nxtDisplayCenteredBigTextLine(0, "AUTO");
	nxtDisplayCenteredBigTextLine(2, "READY");
	nMotorEncoder[mDriveLeft] = 0;
	nMotorEncoder[mDriveRight] = 0;
	//waitForStart();
	nxtDisplayCenteredBigTextLine(2, "RUNNING");
	//StartTask(getSmux);
	StartTask(showDebugInfo);

	//goFeet(2.0, 50);
	goTicks(1325, 50);

}
