#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S2,     SMUX,           sensorI2CCustom)
#pragma config(Sensor, S3,     sGyro,          sensorI2CHiTechnicGyro)
#pragma config(Sensor, S4,     TMUX,           sensorAnalogInactive)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,          mBlockStop,    tmotorNXT, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_1,     mDriveLeft,    tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     mDriveRight,   tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     mBsConveyor,   tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     mBsAngle,      tmotorTetrix, openLoop, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#include "JoystickDriver.c"
#include "autonomous-includes/autonomous_tasks.c"
#include "autonomous-includes/autoMenu.h"

// 1 wheel rotation = 1350 ticks
void initializeRobot(){
	eraseDisplay();														// Clear the screen
	clearDebugStream();												// Clear the debug stream
	//nxtDisplayCenteredBigTextLine(0, "AUTO");	// Print out a message saying we're ready
	//nxtDisplayCenteredBigTextLine(2, "READY");
	nMotorEncoder[mDriveLeft] = 0;						// Set all the encoders to 0
	nMotorEncoder[mDriveRight] = 0;
	nMotorEncoder[mBsAngle] = 0;
	//StartTask(runMenuOffensive);
}

task main()
{
	waitForStart();														// Wait for the green light
//	nxtDisplayCenteredBigTextLine(2, "RUNNING");
	StartTask(getSmux);												// Start getting sensor input
	StartTask(showDebugInfo);									// Print out important info

	suckerToDropPosition();	// Raise the block sucker to dropping position
	goTicks(2125, 50);			// Move up to the baskets
	spitBlock();						// Deposit the block
	goTicks(-1000, 50);			// Back up
	turnDegrees(60, 75);		// Turn left
	goTicks(3000, 100);			// Go forward
	turnDegrees(-45, 75);		// Turn right
	goTicks(4000, 100);			// Go forward

}
