#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S3,     IRS_R,          sensorI2CCustom)
#pragma config(Sensor, S4,     IRS_L,          sensorI2CCustom)
#pragma config(Motor,  mtr_S1_C1_1,     mDriveLeft,    tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     mDriveRight,   tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     mBsConveyor,   tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     mBsAngle,      tmotorTetrix, openLoop, encoder)
#pragma config(Servo,  srvo_S1_C3_1,    sBrickStop,           tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
//#include "autonomous-includes/autonomous_tasks.c"

//#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.


void initializeRobot()
{
  motor[mDriveLeft] = 0;
  motor[mDriveRight] = 0;
  motor[mBsConveyor] = 0;
  motor[mBsAngle] = 0;
//  nMotorEncoder[mBlockStop] = 0;
	nMotorEncoder[mBsAngle] = 0;
	nMotorEncoder[mBsConveyor] = 0;
	nMotorEncoder[mDriveLeft] = 0;
	nMotorEncoder[mDriveRight] = 0;
  return;
}

task main(){

/*	void initializeRobot()
{
  motor[mDriveLeft] = 0;
  motor[mDriveRight] = 0;
  motor[mBsConveyor] = 0;
  motor[mBsAngle] = 0;
  //nMotorEncoder[mBlockStop] = 0;
	nMotorEncoder[mBsAngle] = 0;
	nMotorEncoder[mBsConveyor] = 0;
	nMotorEncoder[mDriveLeft] = 0;
	nMotorEncoder[mDriveRight] = 0;
  return;
}*/

	// do some housekeeping work. print that the program is running, clear the screen and debug stream
	bNxtLCDStatusDisplay = false;
	eraseDisplay();
	nxtDisplayBigTextLine(0, "Auto");
	nxtDisplayBigTextLine(2, "Mode");
	nxtDisplayBigTextLine(4, "Running");
	nxtDisplayTextLine(6, "Running task:");
	clearDebugStream();
	ClearTimer(T1);

	waitForStart();

	//StartTask(getSmux); // run and update the sensor multiplexer
}
