#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S2,     SMUX,           sensorI2CCustom)
#pragma config(Sensor, S3,     sGyro,          sensorI2CHiTechnicGyro)
#pragma config(Sensor, S4,     TMUX,           sensorAnalogInactive)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,          mBlockStop,    tmotorNXT, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_1,     mDriveLeft,    tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     mDriveRight,   tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     mBsConveyor,   tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     mBsAngle,      tmotorTetrix, openLoop, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
#include "autonomous-includes/autonomous_tasks.c"

task main(){
	StartTask(showDebugInfo);
	nMotorEncoder[mDriveLeft] = 0;
	long encoderHome = nMotorEncoder[mDriveLeft];
	StartTask(getSmux);
	tMUXSensor activeIr;
	if(touchInput2)
		activeIr = irRight;
	else
		activeIr = irLeft;

	findIr(activeIr, 60, 25, 25);
	placeBlock(1);
	returnToSpot(1, encoderHome);
	turnDegrees(90);
	findWhiteLine(false, 1);
	turnDegrees(-90);
	goFeet(2, 100);

}
