#pragma config(Sensor, S1,     mTouchSensor,   sensorHiTechnicTouchMux)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "hitechnic-touchmux.h"

int mTouch1;
int mTouch2;
int mTouch3;
int mTouch4;

/*const tMUXSensor rawTouch1 = mTouch1;
const tMUXSensor rawTouch2 = mTouch2;
const tMUXSensor rawTouch3 = mTouch3;
const tMUXSensor rawTouch4 = mTouch4;*/

task main()
{
	while(true)
	{

		nxtDisplayTextLine(1, "Touch1: %d", HTTMUXisActive(mTouchSensor, 1));
		nxtDisplayTextLine(2, "Touch2: %d", HTTMUXisActive(mTouchSensor, 2));
		nxtDisplayTextLine(3, "Touch3: %d", HTTMUXisActive(mTouchSensor, 3));
		nxtDisplayTextLine(4, "Touch4: %d", HTTMUXisActive(mTouchSensor, 4));
	}
	}
