#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,          mBlockStop,    tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

bool		brickBlocked = true;
bool		blockerMoving = false;

const int encoderStartValue = nMotorEncoder[mBlockStop];

const int			blockClosedPos = 0;
const int			blockOpenPos = 90;

// Move the block breaker without stopping the program
task moveBrickBlocker(){
	blockerMoving = true; // Raise the blockerMoving flag
	if(brickBlocked){
		while(nMotorEncoder[mBlockStop] < (encoderStartValue + blockOpenPos)){	// While motor has not reached encoder position
			motor[mBlockStop] = 25;
		}
		writeDebugStreamLine("current encoder value: %d at end", nMotorEncoder[mBlockStop]);
		motor[mBlockStop] = 0;
		brickBlocked = false; // Blocker is now open, toggle flag
	}else{
		while(nMotorEncoder[mBlockStop] > (encoderStartValue + blockClosedPos)){ // While motor has not reached encoder position
			motor[mBlockStop] = -25;
		}
		writeDebugStreamLine("current encoder value: %d at end", nMotorEncoder[mBlockStop]);
		motor[mBlockStop] = 0;
		brickBlocked = true;	// Blocker is now closed, toggle flag
		writeDebugStreamLine("brickBlocked toggled: true\n closed blocker");
	}
	blockerMoving = false; // Toggle off the task flag, and end
	writeDebugStreamLine("Stopped task: moveBrickBlocker");
	return;
}


task main()
{
	ClearTimer(T1);
	clearDebugStream();
	writeDebugStreamLine("current encoder value: %d at start", nMotorEncoder[mBlockStop]);
	blockerMoving = true;
	StartTask(moveBrickBlocker);
	writeDebugStreamLine("Started task: moveBrickBlocker");
	while(blockerMoving){

	}
	wait10Msec(200);
	writeDebugStreamLine("current encoder value: %d at start", nMotorEncoder[mBlockStop]);
	blockerMoving = true;
	StartTask(moveBrickBlocker);
	writeDebugStreamLine("Started task: moveBrickBlocker");
	wait10Msec(300);


}
